### PR TITLE
avoid potential ValueError in Wiki processing

### PR DESCRIPTION
**Pull request by boneskull**
so the good news is this fixes my problem:

```
Collecting API contributors...
Collecting all repo contributors.........................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Collecting wiki contributors.....
Collecting CONTRIBUTORS file...No CONTRIBUTORS file
Traceback (most recent call last):
  File "/usr/local/bin/octohatrack", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/octohatrack/__main__.py", line 62, in main
    all_contributors = unique_users(api_contributors, pri_contributors, wiki_contributors, file_contributors)
  File "/usr/local/lib/python3.5/site-packages/octohatrack/helpers.py", line 156, in unique_users
    p.remove(x)
ValueError: list.remove(x): x not in list
```

the bad news is that I don't know why this happened, nor do I know if this change will break something else.

### CODE REVIEW

**Comment by glasnt** [comment]
Hi @boneskull. Which repo did you run this against, so I can check where the duplicate is coming in?

**Comment by boneskull** [comment]
mochajs/mocha

Sorry for the late reply. Tough to keep up with GitHub

**Comment by glasnt** [comment]
No worries. Thanks for the update. The issue is within some fragile code that I'll cleanup as opposed to just ignoring the issue.

**Comment by glasnt** [comment]
No, you're right. My fragile code was underdocumented, and this fixes it.

**Pull request merged**
