### PR TITLE
Pep8

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Comment by tacaswell** [comment]
I am 50/50 on the last commit as the file was self consistent.  I can re-do all of this at 2 space indent if you want.  I just found it very jarring to read files with mixed indentation :wink: .

**Comment by tacaswell** [comment]
I also did not touch the files octohub.

**Comment by glasnt** [comment]
Hi @tacaswell! Thanks for the PR

I'm not familiar with what the current standard for indenting, formatting, and linting python code automatically is. 

Which tool are you using for this, or is it manual?

Whatever it is, feel free to run it over the entire code base :)

**Comment by tacaswell** [comment]
This was done manually (with the help of pyflakes based highlighting in my editor).

I did not do the octohub code as in my experience it is better to not make local changes to vendored code to reduce conflicts if you decide to update that code in the future.

I am trying to run this code on matplotlib, but have exhausted my gh token 3x now (and have a 39M cache file).

**Comment by glasnt** [comment]
> This was done manually (with the help of pyflakes based highlighting in my editor).

Thank you for your efforts!

> I did not do the octohub code as in my experience it is better to not make local changes to vendored code to reduce conflicts if you decide to update that code in the future.

This makes sense

> I am trying to run this code on matplotlib, but have exhausted my gh token 3x now (and have a 39M cache file).

Ouch. 

Hopefully what you're going to be seeing is getting chunks as the older runs have their results saved. I've tried this once before on a repo with larger sets, and I think it worked, but I hope you're able to get the results you're after eventually

**Comment by glasnt** [comment]
If it's not too much trouble, could you force everything apart from vendor to two space, the rebase this PR? I'll then merge it. 

If you are having more issues with the matplotlib run, I'm happy to take a look, and discuss in an issue.

**Comment by tacaswell** [comment]
Don't merge this just yet, I want to clean up some of the continuation indentation

**Comment by glasnt** [comment]
@tacaswell I won't merge until comment on this thread stating you're ready :)

**Comment by tacaswell** [comment]
ok, done.  I personally like 4 space better, but when in Rome...

**Comment by glasnt** [comment]
I'm not a avid fan of either two or four, but consistency is better than inconsistency. 

Thank you so much for your efforts with this!

**Pull request merged**
